---

#Check if services are present

- include_vars: ../../../groupvars/package.yml

- name: Check if services are present
  stat: path=/etc/init.d/"{{service_name}}"
  register: service_status


- name: Stop service
  service: name="{{service_name}}" state=stopped
  when: service_status.stat.exists
  register: service_stopped