---

#Setting Swappiness to 1 

- name: Get swappiness value
  command: cat /proc/sys/vm/swappiness
  register: actual_swappiness

- name: Set VM Swappiness to 1
  sysctl:
    name: vm.swappiness
    value: 1
    state: present
  when:  actual_swappiness.stdout != 1